# Generated by Django 5.0.2 on 2024-02-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SocialDistribution", "0002_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
