# Generated by Django 5.0.2 on 2024-02-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialDistribution', '0003_post_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends-Only')], default='PUBLIC', max_length=10),
        ),
    ]
