# Generated by Django 5.0.2 on 2024-02-20 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "SocialDistribution",
            "0009_rename_post_like_like_remove_comment_author_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="follower",
            options={"ordering": ["-date_followed"]},
        ),
        migrations.AlterUniqueTogether(
            name="follower",
            unique_together={("follower", "following")},
        ),
        migrations.CreateModel(
            name="Friend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_became_friends", models.DateTimeField(auto_now_add=True)),
                (
                    "user1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friends_set1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friends_set2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_became_friends"],
            },
        ),
        migrations.AddConstraint(
            model_name="friend",
            constraint=models.UniqueConstraint(
                fields=("user1", "user2"), name="unique_friendship"
            ),
        ),
    ]
