# Generated by Django 5.0.2 on 2024-02-21 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SocialDistribution", "0010_alter_follower_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="like",
        ),
        migrations.AddField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                default=99999,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="like",
                to="SocialDistribution.post",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="commenter",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commenters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                default=99999,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to="SocialDistribution.post",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="liker",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
