# Generated by Django 5.0.2 on 2024-02-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialDistribution', '0011_remove_like_like_like_post_alter_comment_commenter_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follower',
            new_name='Follow',
        ),
    ]
