# Generated by Django 5.0.2 on 2024-02-22 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SocialDistribution", "0012_rename_follower_follow"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-date_commented"]},
        ),
        migrations.AlterModelOptions(
            name="like",
            options={"ordering": ["-date_liked"]},
        ),
    ]
